baseurl = "/blog"
languageCode = "en-us"
languageLang = "en"
title = "Mintables Blog"
theme = "coyote"
googleAnalytics = 'G-92DLLFBN49'
staticDir = ['static']
[outputs]
  home = [ "HTML", "RSS", "JSON"]
